### PR TITLE
add flag of the Czech Republic

### PR DESCRIPTION
**Pull request by martinsustek**

### CODE REVIEW

**Comment by martinsustek** [comment]
Please add "hacktoberfest-accepted" label to this PR

**Comment by talgautb** [comment]
@martinsustek thaks for PR, but can you use `stylus` and `jade` and then generate css? now it is not valid

where did you get these colors?

**Comment by martinsustek** [comment]
I've find different sources for colors. Do you use some specific source / pallete?

**Comment by martinsustek** [comment]
Please check it now. I am not sure if to commit generated files.

**Comment by talgautb** [comment]
@martinsustek check colors [here](https://github.com/talgautb/vexillum/issues/6#issuecomment-259441626)

**Comment by talgautb** [comment]
@martinsustek thaks for PR!

**Pull request merged**
